test:
	make -C enum test
	make -C ns test
	make -C inheritance test
	make -C arg_test test
	make -C template_type_param test
clean:
	make -C enum clean
	make -C ns clean
	make -C inheritance clean
	make -C arg_test clean
	make -C template_type_param clean
