#!/usr/bin/env python

import json, sys, re, commands

if len(sys.argv) != 2:
    print "usage: cmd file"
    sys.exit(1)

file = sys.argv[1]

with open(file) as f:
    data = json.load(f)

for i in data:
    argList = re.split("\s+", i["command"])
    cmd = "cxxtags db " + " ".join(argList[1:])
    print cmd
    (rv, out) = commands.getstatusoutput(cmd)
    print out
