#!/usr/bin/python
""" Usage: call with out.db in.db ...
"""

import sys
import os
import tempfile
import sqlite3
import shutil

DB_VER = 4

db_in = None
db_out = None

def merge_ref_db(db_out, db_in_file):
    # concat DBs
    db_out.execute("ATTACH DATABASE '%s' AS src"%(db_in_file))
    db_out.execute("INSERT INTO main.ref(usr, name, file_name, line, col, kind, ref_file_name, ref_line, ref_col) SELECT usr, name, file_name, line, col, kind, ref_file_name, ref_line, ref_col from src.ref")
    db_out.execute("DETACH DATABASE src")
    # remove duplicated rows.
    db_out.execute("CREATE TABLE tmp_table AS SELECT * FROM main.ref GROUP BY usr, name, file_name, line, col, kind, ref_file_name, ref_line, ref_col")
    db_out.execute("DROP TABLE ref");
    db_out.execute("ALTER TABLE tmp_table RENAME TO ref");

def merge_decl_db(db_out, db_in_file):
    # concat DBs
    db_out.execute("ATTACH DATABASE '%s' AS src"%(db_in_file))
    db_out.execute("INSERT INTO main.decl(usr, name, file_name, line, col, kind, val, is_virtual, is_def) SELECT usr, name, file_name, line, col, kind, val, is_virtual, is_def from src.decl")
    db_out.execute("DETACH DATABASE src")
    # remove duplicated rows.
    db_out.execute("CREATE TABLE tmp_table AS SELECT * FROM main.decl GROUP BY usr, name, file_name, line, col, kind, val, is_virtual, is_def")
    db_out.execute("DROP TABLE decl");
    db_out.execute("ALTER TABLE tmp_table RENAME TO decl");

def merge_overriden_db(db_out, db_in_file):
    # concat DBs
    db_out.execute("ATTACH DATABASE '%s' AS src"%(db_in_file))
    db_out.execute("INSERT INTO main.overriden(usr, name, file_name, line, col, kind, usr_overrider, is_def) SELECT usr, name, file_name, line, col, kind, usr_overrider, is_def from src.overriden")
    db_out.execute("DETACH DATABASE src")
    # remove duplicated rows.
    db_out.execute("CREATE TABLE tmp_table AS SELECT * FROM main.overriden GROUP BY usr, name, file_name, line, col, kind, usr_overrider, is_def")
    db_out.execute("DROP TABLE overriden");
    db_out.execute("ALTER TABLE tmp_table RENAME TO overriden");

def get_db_ver(db):
    # get input db
    q = "select db_format from db_info"
    db.execute(q)
    res = db.execute(q).fetchall()
    if len(res) != 1:
        return None
    return res[0][0]

fo = tempfile.NamedTemporaryFile()
#print "tmp: " , fo.name
db_out = sqlite3.connect(fo.name)

db_out.execute(
        u"""
        create table db_info(
            db_format integer
            );
        """
     )
db_out.execute(
        u"""
        create table ref(
            usr text,
            name text,
            file_name text,
            line integer,
            col integer,
            kind text,
            ref_file_name text,
            ref_line integer,
            ref_col integer
            );
        """
     )
db_out.execute(
        u"""
        create table decl(
            usr text,
            name text,
            file_name text,
            line integer,
            col integer,
            kind text,
            val integer,
            is_virtual integer,
            is_def integer);
        """
     )
db_out.execute(
        u"""
        create table overriden(
            usr text,
            name text,
            file_name text,
            line integer,
            col integer,
            kind text,
            usr_overrider text,
            is_def integer
            );
        """
     )
db_out.execute("insert into db_info values(%d);" % (DB_VER))

end = len(sys.argv)
for i in sys.argv[2:end]:
    print "merging tags: ", i
    db_in = sqlite3.connect(i)
    db_ver = get_db_ver(db_in)
    db_in.close()
    if db_ver == None or db_ver != DB_VER:
        print "ERROR: db format mismatch: " + str(db_ver) + " vs. " + str(DB_VER)
        exit(1)
    merge_ref_db(db_out, i)
    merge_decl_db(db_out, i)
    merge_overriden_db(db_out, i)
    db_out.commit()

db_out.close()
fo.flush()
shutil.copy(fo.name, sys.argv[1])
fo.close()
