#!/usr/bin/env python

import json, sys, re, commands

if len(sys.argv) != 3:
    print "usage: cmd db_name proj_file"
    sys.exit(1)

dbname = sys.argv[1]
filename = sys.argv[2]

with open(filename) as f:
    data = json.load(f)

for i in data:
    argList = re.split("\s+", i["command"])
    cmd = "cxxtags " + dbname + " " + " ".join(argList[1:])
    (rv, out) = commands.getstatusoutput(cmd)
    print out
